### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by buracat** [mateoradic16/pterodactyl-unturned2#1]
??

**Comment by mateoradic16** [comment]
Download this egg file:
https://mega.nz/#!Fc1VSbyJ!x0Zyv3DqMqEbkZvm4lTyeYQIKbtxcnA10U2pXdFvdGM

Go to your panel, login as admin, go to nests, click on Import Egg and choose file that u downloaded, then choose Source Engine as Associated Nest and thats it.

**Comment by mateoradic16** [comment]
If you need any other help u can add me on discord Teo#7096

**Comment by buracat** [comment]
thanks :)
